<?php
    $titulo = 'Deletar album';
    $this->headTitle($titulo);
?>

<h1><?php echo $this->escapeHtml($titulo); ?></h1>

<p>
    Are you sure that you want to delete
    '<?php echo $this->escapeHtml($album->titulo); ?>' by
    '<?php echo $this->escapeHtml($album->artista) ?>'?
</p>

<?php
    $url = $this->url('album', array(
        'action'    => 'delete',
        'id'        => $this->id
    ));
?>

<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $album->id ?>" />
        <input type="submit" name="del" value="Yes">
        <input type="submit" name="del" value="No">
    </div>
</form>