<?php
    $titulo = 'Editar album';
    $this->headTitle($titulo);
?>

<h1><?php echo $this->escapeHtml($titulo); ?></h1>

<?php
    $form = $this->form;

    $form->setAttribute(
        'action',
        $this->url('album',
            array(
                'action' => 'edit',
                'id'     => $this->id
            )
        )
    );
    $form->prepare();

    echo $this->form()->openTag($form);

    echo $this->formCollection($form);

    echo $this->form()->closeTag();

?>